/**
 * Kanji Krate
 * Kanji Krate backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDeckDto { 
    /**
     * Version key
     */
    __v: number;
    /**
     * The name of the deck
     */
    name: string;
    /**
     * The description of the deck
     */
    description: string;
    /**
     * The owner of the deck
     */
    owner: object;
    /**
     * Array of Card ObjectIds
     */
    cards?: Array<string>;
}

