/**
 * Kanji Krate
 * Kanji Krate backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Deck { 
    createdDate: string;
    updatedDate: string;
    deletedDate: string;
    __v: number;
    _id: string;
    name: string;
    description?: string;
    owner?: string;
    /**
     * Array of Card ObjectIds
     */
    cards: Array<string>;
}

