/**
 * Kanji Krate
 * Kanji Krate backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReadByFieldDto { 
    /**
     * take value
     */
    take?: number;
    /**
     * skip value
     */
    skip?: number;
    /**
     * document to populate
     */
    populate?: string;
    /**
     * Field to search by
     */
    field: string;
    /**
     * Optional boolean value
     */
    boolValue?: boolean;
    /**
     * Optional string value
     */
    stringValue?: string;
    /**
     * Optional int value
     */
    intValue?: number;
    /**
     * Optional _id value
     */
    objectId?: string;
}

