/**
 * Kanji Krate
 * Kanji Krate backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    createdDate: string;
    updatedDate: string;
    deletedDate: string;
    __v: number;
    _id: string;
    googleUserId: string;
    active: boolean;
    email?: string;
    password?: string;
    locale?: string;
    name?: string;
    permissions: Array<string>;
}

